### PR TITLE
expanded home cards and changed busyness to activity

### PR DESCRIPTION
**Pull request by esduh**

### CODE REVIEW

**Comment by esduh** [comment]
- Home screen cards now display Estimated Numbers and Report Activity button. 
Still discussing the details for Estimated Numbers.. 
- Changed all titles starting with "business" or "busyness" (ex. getBusynessStyle) to "activity" (ex. getActivityStyle)

**Comment by zctg88** [comment]
Hey Esther! I'm got a lot of errors when I tried to run your branch, do you know what they mean?
Screen Shot 2020-10-19 at 9 48 17 PM

**Comment by esduh** [comment]
Hey Zach! Hmm, it seems to be working on my end.. though I did notice a big error like that too when I ran the code earlier and it clicked into the map page.. I wonder what the problem is?

**Comment by zctg88** [comment]
Let's discuss this on Tuesday during our meeting and hopefully we can figure out what the error is and merge the branch cleanly :))

**Comment by Leo-SIK** [comment]
I don't have any errors!

**Comment by zctg88** [comment]
Updated name of branch to "features/home-screen-cards"

**Pull request closed without merging**
