### PR TITLE
pushed changes to alter the button colors on report page

### PR DESCRIPTION
**Pull request by sinai228**
I looked back at the demo, but it didn't seem like we had to scroll to see the rest of the buttons; 
hmm.. 
I'll mention this on our Thursday meeting as well as the color change(gray) when we select on one of the activity report buttons

### CODE REVIEW

**Comment by zctg88** [comment]
Sorry about that, I forgot that I used two different devices. The buttons went off the screen on the iPhone SE, 1st gen, but there was no need to scroll on the iPhone SE, 2nd gen. I still think Prof. VL wants us to have smaller buttons such that they can fit in a grid rather than the single column that they are in now.

**Comment by zctg88** [comment]
Also, are you able to use lighter colors/create a more distinct contrast between the buttons? I feel like those that are less perceptive of color lightness won't be able to tell the difference between the dark grey and dark maroon.

**Comment by kvlinden** [comment]
Is this the lab 11 pull request to review?

**Comment by zctg88** [comment]
This isn't the branch to review, I shall make you a reviewer on a new pull request for a different branch?

**Pull request closed without merging**
